### ISSUE TITLE
Is participation as public IE allowed bug

### ISSUE THREAD

**Issue by plehegar** [w3c/Unitas#81]
https://labs.w3.org/unitas/?g=101220
says that participation as public IE isn't allowed.

But https://www.w3.org/groups/w3cgroups/101220 says otherwise.

**Comment by tripu** [comment]
[The corresponding API request (append a valid API key)](https://api.w3.org/groups/101220?embed=true) contains  
`"participation-as-public-ie-allowed": false`  
, so I suspect it's not an issue in Unitas.

It could be caching, it could be a bug in the API. I just filed an internal issue about this.
