### ISSUE TITLE
broken on Firefox + NOSCRIPT

### ISSUE THREAD

**Issue by tantek** [w3c/Unitas#82]
https://w3c.github.io/Unitas/ fails on Firefox with the NOSCRIPT add-on (quite common among web devs etc.), even with all of its scripts whitelisted.

All I see is:

W3C                            
[Loading…]
Copyright © 2016–2017 W3C.
0%

And it just sits there. Also the gear spins when I hover but is otherwise non-functional.

**Comment by dwsinger** [comment]
gear also spins in safari non-functionally

**Comment by tripu** [comment]
Client-side JavaScript is a requirement of Unitas, @tantek.

If that's an issue, there are other clients of the [public W3C API](https://w3c.github.io/w3c-api/) that can be used server-side, eg [npm package `node-w3capi`](https://www.npmjs.com/package/node-w3capi).

I'm not familiar with that particular browser extension. If all scripts originating from the necessary origins (`https://cdnjs.cloudflare.com`, `https://w3c.github.io`, `https://code.jquery.com`, `https://maxcdn.bootstrapcdn.com`&hellip;) are whitelisted, I think it should work&hellip;

**Comment by tantek** [comment]
"are whitelisted, I think it should work" ... that's the crux of this issue, it does not work, even with whitelisting.

**Comment by tripu** [comment]
@tantek:
I just tried (Ubuntu 17.04, Firefox 56.0 64-bit, NoScript 5.1.2). I visited `https://w3c.github.io/Unitas/`, clicked on &ldquo;Allow all this page&rdquo;, reloaded the page, and it works normally.

Can you provide more details? Are you sure you're whitelisting *all* resources?

Thanks.

**Comment by tripu** [comment]
@dwsinger: sorry, how/when does it fail in Safari? And are you using that same extension, and whitelisting Unitas' resources, too?

**Comment by dwsinger** [comment]
I didn't realize I needed an extension or whitelisting...

**Comment by tripu** [comment]
> *&ldquo;I didn't realize I needed an extension or whitelisting...&rdquo;*

No, that's the thing: you don't need an extension for Unitas to work. Just a modern browser interpreting JavaScript.

If Unitas is not working for you on Safari, that may be a bug, @dwsinger.

Can you please tell me your OS and Safari version?
Also, could you check the JavaScript console and the &ldquo;network&rdquo; tab in [Safari's developer tools](https://developer.apple.com/safari/tools/), and see if there are JS errors, resources being blocked, error codes, etc?

A screenshot might help too, to understand how it's failing (is it just those gears at the top, or is the page not showing any items at all? etc).

Thank you beforehand for following up.

**Comment by tripu** [comment]
@tantek, @dwsinger: can you provide detailed steps to reproduce this issue, please? If not, I'm closing it&hellip;

**Comment by dwsinger** [comment]
close it for now.  I'll dig when I have time
